export const FontFamily = {
    Regular: 'Roboto-Regular',
    Italic: 'Roboto-Italic',
    Bold: 'Roboto-Bold',
    BoldItalic: 'Roboto-BoldItalic',
    ExtraBold: 'Roboto-ExtraBold',
    ExtraBoldItalic: 'Roboto-ExtraBoldItalic',
    ExtraLight: 'Roboto-ExtraLight',
    ExtraLightItalic: 'Roboto-ExtraLightItalic',
    Light: 'Roboto-Light',
    LightItalic: 'Roboto-LightItalic',
    Medium: 'Roboto-Medium',
    MediumItalic: 'Roboto-MediumItalic',
    SemiBold: 'Roboto-SemiBold',
    SemiBoldItalic: 'Roboto-SemiBoldItalic',
    Thin: 'Roboto-Thin',
    ThinItalic: 'Roboto-ThinItalic',
    Black: 'Roboto-Black',
    BlackItalic: 'Roboto-BlackItalic',
};